
name: Build Spectra

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install ShadowProver
      run: |
        git clone https://github.com/rairlab/shadowprover
        cd shadowprover
        mvn package install
    
    - name: Checkout Spectra
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Build With Maven
      run: mvn package
